### ISSUE TITLE
Step 3

### ISSUE THREAD

**Issue by Rahulmethari** [wouterbulten/ACAIS2013Workshop#1]
Hello I'm stuck at step 3 near import wanderer please help

**Comment by wouterbulten** [comment]
Hi, you are probably stuck because Breve is not available on your system. Unfortunately the breve project has been discontinued a few years ago. Do you have a version of it available on your machine?

**Comment by Rahulmethari** [comment]
Yes I've installed breve, the only mistake i did was I didn't know that we
have to download wanderer.py. Now its working fine. I'll contact you if
have any doubts.
Thank you.

**Comment by wouterbulten** [comment]
Good to hear. Let me know if you encounter any problems.
